# Place all the behaviors and hooks related to the matching controller here.
# All this logic will automatically be available in application.js.
# You can use CoffeeScript in this file: http://coffeescript.org/

$ ->
	$('#tile1').click ->
		$('#tile1').addClass('activetile')
		$('#home-content-home').removeClass('hidden')
		$('#tile2').removeClass('activetile')
		$('#home-content-history').addClass('hidden')
		$('#tile3').removeClass('activetile')
		$('#home-content-now').addClass('hidden')
		$('#tile4').removeClass('activetile')
		$('#home-content-door').addClass('hidden')
		$('#tile5').removeClass('activetile')
		$('#home-content-tour').addClass('hidden')
		$('#tile6').removeClass('activetile')
		$('#home-content-location').addClass('hidden')
	
	$('#tile2').click ->
		$('#tile1').removeClass('activetile')
		$('#home-content-home').addClass('hidden')
		$('#tile2').addClass('activetile')
		$('#home-content-history').removeClass('hidden')
		$('#tile3').removeClass('activetile')
		$('#home-content-now').addClass('hidden')
		$('#tile4').removeClass('activetile')
		$('#home-content-door').addClass('hidden')
		$('#tile5').removeClass('activetile')
		$('#home-content-tour').addClass('hidden')
		$('#tile6').removeClass('activetile')
		$('#home-content-location').addClass('hidden')
	
	$('#tile3').click ->
		$('#tile1').removeClass('activetile')
		$('#home-content-home').addClass('hidden')
		$('#tile2').removeClass('activetile')
		$('#home-content-history').addClass('hidden')
		$('#tile3').addClass('activetile')
		$('#home-content-now').removeClass('hidden')
		$('#tile4').removeClass('activetile')
		$('#home-content-door').addClass('hidden')
		$('#tile5').removeClass('activetile')
		$('#home-content-tour').addClass('hidden')
		$('#tile6').removeClass('activetile')
		$('#home-content-location').addClass('hidden')
	
	$('#tile4').click ->
		$('#tile1').removeClass('activetile')
		$('#home-content-home').addClass('hidden')
		$('#tile2').removeClass('activetile')
		$('#home-content-history').addClass('hidden')
		$('#tile3').removeClass('activetile')
		$('#home-content-now').addClass('hidden')
		$('#tile4').addClass('activetile')
		$('#home-content-door').removeClass('hidden')
		$('#tile5').removeClass('activetile')
		$('#home-content-tour').addClass('hidden')
		$('#tile6').removeClass('activetile')
		$('#home-content-location').addClass('hidden')

	$('#tile5').click ->
		$('#tile1').removeClass('activetile')
		$('#home-content-home').addClass('hidden')
		$('#tile2').removeClass('activetile')
		$('#home-content-history').addClass('hidden')
		$('#tile3').removeClass('activetile')
		$('#home-content-now').addClass('hidden')
		$('#tile4').removeClass('activetile')
		$('#home-content-door').addClass('hidden')
		$('#tile5').addClass('activetile')
		$('#home-content-tour').removeClass('hidden')
		$('#tile6').removeClass('activetile')
		$('#home-content-location').addClass('hidden')

	$('#tile6').click ->
		$('#tile1').removeClass('activetile')
		$('#home-content-home').addClass('hidden')
		$('#tile2').removeClass('activetile')
		$('#home-content-history').addClass('hidden')
		$('#tile3').removeClass('activetile')
		$('#home-content-now').addClass('hidden')
		$('#tile4').removeClass('activetile')
		$('#home-content-door').addClass('hidden')
		$('#tile5').removeClass('activetile')
		$('#home-content-tour').addClass('hidden')
		$('#tile6').addClass('activetile')
		$('#home-content-location').removeClass('hidden')